[package]
name = "retrorust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
cpal = "0.14.1"
device_query = "1.1.1"
minifb = "0.23"

[[bin]]
name = "main"
path = "./src/main.rs"